### ISSUE TITLE
Support offline mode (not using Tadiran's/Other server)

### ISSUE THREAD

**Issue by idansk** [hllhll/HomeAssistant-EKON-iAircon#1]
This should basically be done by MITMing the communication between the AC to the server - probably just updates, routing those to the local (HASS?) server and vice versa.

**Comment by hllhll** [comment]
That's a neat idea, but how do u recommend implementing it?
Thought about few alternatives.

1. Use AD-Hoc wifi network for the ekon component (unly usable on rpi/linux and also requires the host to be close enugth) :(
2. Configure local router to pass DNS request to a DNS server controlled by us(delays, issues, HA would probably have a hard time figuring out real DNS) :(
3. ARP Posining - not reliable (at least when using Cain&Able) :(

Another options is to reverse engineer the serial protocol between the AC and the Display. This is on my bucket list, but will take time.
the iAircon is esp8266-based so it is up-gradable, theoretically.

**Comment by hllhll** [comment]
Let's use https://github.com/hllhll/HomeAssistant-EKON-iAircon/issues/19 to discuss, It starts-off a much more easier way to do this...
