### ISSUE TITLE
Error while setting up Ekon

### ISSUE THREAD

**Issue by liorm0505** [hllhll/HomeAssistant-EKON-iAircon#12]
**Describe the bug**
component not loading after updating to the latest commit

**Configuration**
```
climate:

  - platform: ekon
    username: xxx
    password: xxx
    #base_url: https://www.airconet.xyz/
    base_url: https://www.activate-ac.com/
    # name_mapping: 
    #   - id : 2258
    #     name: Living Room AC
```

**Platform:**
 - OS:  HASSIO
 - Version 0.114

```
Error while setting up ekon platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ekon/climate.py", line 189, in async_setup_platform
    await controller.async_load_init_data()
  File "/config/custom_components/ekon/climate.py", line 223, in async_load_init_data
    newdev = EkonClimate(self, dev_raw['mac'], dev_raw['id'],
  File "/config/custom_components/ekon/climate.py", line 433, in __init__
    self.cpy_current_to_set_to()
  File "/config/custom_components/ekon/climate.py", line 437, in cpy_current_to_set_to
    self._set_values._current_humidity = self._current_humidity
AttributeError: 'EkonClimate' object has no attribute '_current_humidity'
```

**Comment by hllhll** [comment]
Thank you, interesting note,
Are you using tadiran connect? Airconet? or Airconet+?

**Comment by liorm0505** [comment]
Airconnect+

Actually i only realized i  using Airconnet+ after i opened the issue (copied the code from the [PR](https://github.com/hllhll/HomeAssistant-EKON-iAircon/pull/11)) . 
So currently it is not related to you code. However, this might be relevant if you merge.

**Comment by hllhll** [comment]
Relevant to the fork with the support for the humidity-enriching entity. I Don't think I'll merge that any time soon...
Can't it be done with other HA tooks to combine the AC and the Humidity sensor instead of combining it in code?
