### ISSUE TITLE
Support for custom entity id

### ISSUE THREAD

**Issue by liorm0505** [hllhll/HomeAssistant-EKON-iAircon#2]
Is it possible to change the entity name other than ekon (default one) ?

**Comment by hllhll** [comment]
Not possible at the moment, a little tricky since you only configure the user and the rest is pulled off the servers. One option is to match the ACid (today ekon.XXXXX) to a user defined string.

Also you could probably get away with it by using templates, try it first. (Any features that I personally don't need might take a while, feel free to contribute :P )

**Comment by liorm0505** [comment]
Hi, 

Does this mean we can set a custom entity ID via the configuration.yaml?
if yes, than for some reason i am still getting an "ekon298" name.
 - platform: ekon
      name: Living Room AC
      username: my@user.name
      password: mypassword
      base_url: https://www.airconet.xyz/

what am i missing here?

**Comment by hllhll** [comment]
That's a quick one I Have not yet updated the README,
`
climate: 
- platform: ekon
...
...
  name_mapping:
    - id: xxxx
      name: MyHvac
`

**Comment by liorm0505** [comment]
Well, i figured you had some time to work on it on Saturday ;)
Keep you updated.

Thanks,

**Comment by hllhll** [comment]
FYI, `id` (and for everyone eise) is just the number that was originally in the EkonXXX

**Comment by liorm0505** [comment]
Does that mean i have to hard code the original id to the configuration file?

**Comment by hllhll** [comment]
Yup. I Name/match the entities according their `id` in ekon systems (the id is generated on server-side and is consistent, not locally)

**Comment by liorm0505** [comment]
I am getting the following error while trying to set the component:

Error while setting up ekon platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/ekon/climate.py", line 174, in async_setup_platform
    await controller.async_load_init_data()
  File "/config/custom_components/ekon/climate.py", line 200, in async_load_init_data
    matching_items = list(filter(lambda x: int(x['id'])==int(dev_raw['id']), self._name_mapping))
  File "/config/custom_components/ekon/climate.py", line 200, in <lambda>
    matching_items = list(filter(lambda x: int(x['id'])==int(dev_raw['id']), self._name_mapping))
KeyError: 'id'

My configuration file:
  - platform: ekon
    username: xxx
    password: xxx
    base_url: https://www.airconet.xyz/
    name_mapping: 
      - id : 2852
      - name: Living_Room_AC

Thanks,

**Comment by liorm0505** [comment]
Found my error:
The correct config is as follows:

  - platform: ekon
    username: xxxx
    password: xxxx
    base_url: https://www.airconet.xyz/
    name_mapping: 
      - id : 2852
        name: Living_Room_AC

(note: "name" shell not have "-")
