### ISSUE TITLE
Add SSL Certificate checking bypass option

### ISSUE THREAD

**Issue by hllhll** [hllhll/HomeAssistant-EKON-iAircon#4]
Since EKON Servers aren't reliable in terms of proper SSL and certificate, add a way so that the user can configure to bypass the SSL Checking (of python).

*NOTE: U Will be prone to an attacker stealing your ekon username&password if you activate this.

**Comment by leranp** [comment]
I am not an expert, but i think that HA is not supported TLS 1.2 ( that this is the version of the iAircon servers)
I have looked at the MQTT component in HA and saw that this is an option to force the connection to work with TLS 1.2
Maybe this is the solution for this problem

**Comment by hllhll** [comment]
I'm sort of an expert, but not really on HA;
I Have not updated my HA for a very long time, and it once worked, now it doesn't.
If you check the certificate path you see on [some](https://www.sslshopper.com/ssl-checker.html#hostname=http://airconet.info/) [sites](https://www.digicert.com/help/) that the certificate is either not trusted or an Intermediary certificate requires external download. Also according to [this ](https://www.cdn77.com/tls-test) the server supports up to 1.2 and below

**Comment by leranp** [comment]
take a look in the MQTT component
https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/__init__.py
And try to force tls 1.2

**Comment by HawkUser** [comment]
Hi,
So far i bypassed the issue by adding "Verify=false" to the Get & Post requests.
Not smart move, but working :)
