### ISSUE TITLE
HA (version 0.110) have changed the climate component, please replace "ClimateDevice" to "ClimateEntity" in climate.py to fix it

### ISSUE THREAD

**Issue by leranp** [hllhll/HomeAssistant-EKON-iAircon#5]
**Describe the bug**

**To Reproduce**

**Configuration**
Share your YAML here

**Expected behavior**

**Screenshots**

**Platform:**
 - OS: [e.g. HASSIO, Hassbian]
 - Version [e.g. 0.92.1]

**Additional context**

**Comment by hllhll** [comment]
Hi, Please tell me if it solved that (I Don't remember seeing this originally on my setup).
