### ISSUE TITLE
Sunset of Airconet (moved to Airconet+)

### ISSUE THREAD

**Issue by HawkUser** [hllhll/HomeAssistant-EKON-iAircon#9]
The current plugin will be obsolete as Airconet removed from the appstores, and moved to airconet+

the new platform works differently. when doing network trace the app facing:
https://www.activate-ac.com/control/turnOnOffDevices?mac=XXXXXXXXXX&onOrOff=true

https://www.activate-ac.com/control/checkDevicesCurrentStatus/60XXXXXXXXXXXXXX

**Comment by rhayun** [comment]
i just open a pull request https://github.com/hllhll/HomeAssistant-EKON-iAircon/pull/10
